### ISSUE TITLE
Telegram url not working

### ISSUE THREAD

**Issue by zoeperman** [Pyenb/Watchtower-telegram-notifications#1]
Hi,

followed the guide, but the telegram url seems to have a / in it wich doesn't work anymore
url format is telegram://token@telegram?chats=channel-1[,chat-id-1,...]
see: https://containrrr.dev/shoutrrr/v0.8/services/telegram/

bad:
WATCHTOWER_NOTIFICATION_URL=telegram://HTTP_API_TOKEN@telegram/?channels=CHAT_ID
good:
WATCHTOWER_NOTIFICATION_URL=telegram://HTTP_API_TOKEN@telegram?channels=CHAT_ID

**Comment by Pyenb** [comment]
Ah ok, thanks. I will fix it in the main repo. But oddly enough it is still working perfectly fine for me
